version: "3.9"
   
services:

  web:
    container_name: denison-jobs-app
    build: .
    command: venv/bin/python main.py
    ports:
      - "7345:7345"
    environment: 
      - REDIS_URL_1=redis://denison-jobs
      - REDIS_URL_2=redis://denison-jobs-emails
    depends_on:
      - denison-jobs
      - denison-jobs-emails

  denison-jobs:
    container_name: denison-jobs
    image: redis
    expose: 
      - "7346"

  denison-jobs-emails:
    container_name: denison-jobs-emails
    image: redis
    expose:
      - "7347"

# secrets:                        # top level secrets block
#   mail_address:
#     file: true
#   mail_pw:
#     file: my_file_secret.txt