version: "3.9"
   
services:
  web:
    container_name: denison-jobs-app
    build: .
    command: venv/bin/python main.py
    ports:
      - "7345:7345"
    depends_on:
      - denison-jobs
      - denison-jobs-emails

  denison-jobs:
    container_name: denison-jobs
    command: redis-server /data/denison-jobs/redis.conf
    image: redis
    ports:
      - "7346:7346"
    volumes:
      - ${PWD}/redis/redis.conf:/data/denison-jobs/redis.conf

  denison-jobs-emails:
    container_name: denison-jobs-emails
    command: redis-server /data/denison-jobs-emails/redis.conf
    image: redis
    ports:
      - "7347:7347"
    volumes:
      - ${PWD}/redis/redis.conf:/data/denison-jobs-emails/redis.conf
  