#! /bin/bash
output_file=secrets.env
output_temp=temp.env
file=/run/secrets/env
rm -f $output_temp
while read line; do
    key=$(echo $line | cut -d = -s -f1 | xargs)
    val=$(echo $line | cut -d = -s -f2 | xargs)
    if [ ! -z "$key" ]; then
        if [ ! -z "$val" ]; then
            echo $key=$val >> $output_temp
        fi
    fi
done < "${file}"
cp $output_temp $output_file
rm -f $output_temp
